//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.Language.Bot.Types.BotError {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phoenix.Language.Bot.Types.BotError.ErrorMessageResources", typeof(ErrorMessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no access to the action you are trying to enter. Please select a valid one..
        /// </summary>
        public static string ActionForbidden {
            get {
                return ResourceManager.GetString("ActionForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected action is temporarily not available..
        /// </summary>
        public static string ActionNotAvailable {
            get {
                return ResourceManager.GetString("ActionNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The student is not yet enrolled to any courses..
        /// </summary>
        public static string AffiliatedUserNotEnrolledToCourses {
            get {
                return ResourceManager.GetString("AffiliatedUserNotEnrolledToCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User authentication failed..
        /// </summary>
        public static string AuthFailed {
            get {
                return ResourceManager.GetString("AuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum limit of failed authentication attempts..
        /// </summary>
        public static string AuthMaxFails {
            get {
                return ResourceManager.GetString("AuthMaxFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no exams for the selected course yet..
        /// </summary>
        public static string CourseHasNoExams {
            get {
                return ResourceManager.GetString("CourseHasNoExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no lectures for the selected course yet..
        /// </summary>
        public static string CourseHasNoLectures {
            get {
                return ResourceManager.GetString("CourseHasNoLectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no affiliated users found for your account..
        /// </summary>
        public static string ParentHasNoAffiliations {
            get {
                return ResourceManager.GetString("ParentHasNoAffiliations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunatelly, there is a problem with your role..
        /// </summary>
        public static string RoleNotValid {
            get {
                return ResourceManager.GetString("RoleNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School&apos;s connection is not active..
        /// </summary>
        public static string SchoolNotConnected {
            get {
                return ResourceManager.GetString("SchoolNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no school found associated with this page..
        /// </summary>
        public static string SchoolNotFound {
            get {
                return ResourceManager.GetString("SchoolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunatelly, an unknown error occured..
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no exams added yet to any course..
        /// </summary>
        public static string UserHasNoExams {
            get {
                return ResourceManager.GetString("UserHasNoExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no lectures added yet to any course..
        /// </summary>
        public static string UserHasNoLectures {
            get {
                return ResourceManager.GetString("UserHasNoLectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will have to read and accept the terms &amp; conditions before we can start..
        /// </summary>
        public static string UserNotAcceptedTerms {
            get {
                return ResourceManager.GetString("UserNotAcceptedTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not yet enrolled to any courses..
        /// </summary>
        public static string UserNotEnrolledToCourses {
            get {
                return ResourceManager.GetString("UserNotEnrolledToCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no access to the school you are attempting to connect to..
        /// </summary>
        public static string UserNotSubscribedToSchool {
            get {
                return ResourceManager.GetString("UserNotSubscribedToSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist anymore..
        /// </summary>
        public static string UserNotValid {
            get {
                return ResourceManager.GetString("UserNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number does not belong to any user anymore..
        /// </summary>
        public static string UserPhoneNotFound {
            get {
                return ResourceManager.GetString("UserPhoneNotFound", resourceCulture);
            }
        }
    }
}
